workflows:
  build:
    name: Build iOS App
    max_build_duration: 120
    instance_type: mac_mini_m1
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/iphoneos/Runner.app.dSYM
      - build/ios/ipa/*.ipa
    cache:
      directories:
        - build
