workflows:
  acs-check:
    name: ACS Check Build
    max_build_duration: 120
    instance_type: mac_mini_m1  
    environment:
      flutter: stable

    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build for iOS
        script: flutter build ipa --release


    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
