workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS and Android
        script: |
          flutter build ios --release
          flutter build apk --release
    artifacts:
      - build/ios/iphoneos/*.ipa
      - build/app/outputs/flutter-apk/*.apk
    cache:
      directories:
        - build
