workflows:
  acs-check:
    name: ACS Check Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Set up code signing
        script: |
          app-store-connect fetch-signing-files
          xcode-project use-profiles
      - name: Build for iOS
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
