workflows:
  build:
    name: Build iOS App
    max_build_duration: 120
    instance_type: mac_mini_m1
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
      - name: List Build Directory
        script: |
          ls -R build/
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.app.dSYM
      - build/ios/archive/*.ipa
